<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bike</name>
   <tag></tag>
   <elementGuidId>594eb254-d194-4ccf-b010-7e670c964e5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.home-view-vendor-types-item--vendor-wrapper__vendor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='orders_container']/div[3]/div/div[2]/div/div/div[3]/div/div[2]/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home-view-vendor-types-item--vendor-wrapper__vendor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Bike
                 
                  
                </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orders_container&quot;)/div[@class=&quot;homeview--outer&quot;]/div[@class=&quot;homeview--inner&quot;]/div[2]/div[1]/div[@class=&quot;home-view-vendor-and-optins-wrappper&quot;]/div[@class=&quot;home-view-vendor-classes&quot;]/div[@class=&quot;home-view-vendor-classes--body&quot;]/div[@class=&quot;home-view-vendor-types&quot;]/div[1]/div[@class=&quot;home-view-vendor-types--item home-view-vendor-types-item-wrap home-view-vendor-types--item__active&quot;]/div[@class=&quot;home-view-vendor-types-item home-view-vendor-types-item--vendor-wrapper&quot;]/div[@class=&quot;home-view-vendor-types-item--vendor-wrapper__vendor&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orders_container']/div[3]/div/div[2]/div/div/div[3]/div/div[2]/div/div/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='large'])[1]/following::div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='medium'])[1]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KES 371'])[1]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
