<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_What type of pickup do you want_el-select__caret el-input__icon el-icon-arrow-up is-reverse</name>
   <tag></tag>
   <elementGuidId>d2b993c3-4b4b-45db-ae98-809f3539a9b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.el-select__caret.el-input__icon.el-icon-arrow-up.is-reverse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='orders_container']/div[3]/div/div/div/div/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/span/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select__caret el-input__icon el-icon-arrow-up is-reverse</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orders_container&quot;)/div[@class=&quot;homeview--outer&quot;]/div[@class=&quot;homeview--inner&quot;]/div[1]/div[1]/div[@class=&quot;extended-options-wrappper&quot;]/div[@class=&quot;home-view-vendor-types-item-wrap home-next-step&quot;]/div[@class=&quot;home-view-carrier-type&quot;]/div[@class=&quot;home-view-truck-options-wrapper&quot;]/div[2]/div[2]/div[@class=&quot;home-view-truck-options-inner-wrapper&quot;]/div[@class=&quot;home-view-truck-options-inner--full-select&quot;]/div[@class=&quot;el-select&quot;]/div[@class=&quot;el-input el-input--suffix is-focus&quot;]/span[@class=&quot;el-input__suffix&quot;]/span[@class=&quot;el-input__suffix-inner&quot;]/i[@class=&quot;el-select__caret el-input__icon el-icon-arrow-up is-reverse&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orders_container']/div[3]/div/div/div/div/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/span/span/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
   </webElementXpaths>
</WebElementEntity>
