<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KES 0_paymentOptions</name>
   <tag></tag>
   <elementGuidId>9fae71ba-ac96-4386-b6fc-088e0dfea32d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='paymentOptions'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentOptions</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment__radio-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orders_container&quot;)/div[@class=&quot;homeview--outer&quot;]/div[@class=&quot;homeview--inner&quot;]/div[1]/div[1]/div[@class=&quot;extended-options-wrappper&quot;]/div[@class=&quot;home-view-vendor-types-item-wrap home-next-step&quot;]/div[@class=&quot;home-view-carrier-type&quot;]/div[@class=&quot;home-view-truck-options-wrapper&quot;]/div[@class=&quot;home-view-truck-options-inner-wrapper&quot;]/div[@class=&quot;home-view-vendor-classes--label&quot;]/div[1]/div[@class=&quot;home-view-actions--note&quot;]/div[@class=&quot;home-view-notes-wrapper&quot;]/div[1]/span[1]/div[@class=&quot;home-view-notes-wrapper--item home-view-notes-wrapper--item__row&quot;]/div[@class=&quot;home-view-notes-wrapper--item__option&quot;]/div[@class=&quot;home-view-notes-wrapper--item__option-div payment__radio-button-label&quot;]/input[@class=&quot;payment__radio-button&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='paymentOptions'])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orders_container']/div[3]/div/div/div/div/div/div[2]/div/div[3]/div/div/div[2]/div[2]/div/span/div[4]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
